language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r dev-requirements.txt
    - pip install codecov
    - pip install -e .

before_script:
    - git config --global user.name 'Travis CI and ön'
    - git config --global user.email 'test@exmaple.com'

script:
    - make test

after_success:
  - codecov

notifications:
    email: false
